version: '2'
services:
  server:
    image: ubuntu

  nginx:
    image: nginx:1.15.8-alpine
    ports:
      - 80:81
    volumes:
      - ./build_containers/nginx:/var/www/html
      - ./build_containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build_containers/nginx/conf.d:/etc/nginx/conf.d
  hhvm:
    build: build_containers/hhvm
    ports:
      - 3606:3606
    volumes:
      # - マウントしたいホストマシンのディレクトリを指定:/app
      - ./build_containers/hhvm/hh.conf:/etc/hh.conf
      - ./build_containers/hhvm/php.ini:/etc/hhvm/php.ini
      - ./build_containers/hhvm/server.ini:/etc/hhvm/server.ini
    depends_on:
      - nginx
      - mysql
    tty: true

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
